name: Release package

env:
  NUGET_SOURCE_URL: https://nuget.pkg.github.com/AndrewMJordan
  NUGET_PROJECT_DIR: src/To/To.csproj

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          source-url: ${{env.NUGET_SOURCE_URL}}/index.json
      - run: |
          dotnet build --configuration Release "${{env.NUGET_PROJECT_DIR}}"
          dotnet pack --configuration Release "${{env.NUGET_PROJECT_DIR}}" --no-build --output .
          dotnet nuget push *.nupkg --api-key ${{secrets.GITHUB_TOKEN}}
